= Welcome to the fool's voyage in the world of 8bit emulation and basic interpreters

A blow by blow account of my futile attemps at emulating the computers, consoles and arcades I grew up with. Done for no other reason than to see if I can. If it helps others along the way, then that's a bonus!

== Introduction

So I am not really starting from scratch, I have previous !!!

Since late 2019 i have been writing code off and on around these subjects.

It started with the Cult of the bound Variable. (http://www.boundvariable.org/task.shtml). The first part of which was to write an emulator for a weird pre-historic computer, part of the 2006 ICFP programming contest. I wrote a basic emulator in Python, Go, Swift, C and C++.  

This was a great learning experience, and I was hooked. I then went on to write a CHIP-8 emulator in GO and more recently in Python. 

I then started amusing myself and wrote a basic interpreter, covering all of TinyBasic and more in C and C++, complete with full screen editor and line editor.

But none of these were ever really finished and polished, I suppose it is the priviledge og the hobbyist to be able to move on to the next shiny thing as soon as the current one becomes boring.