= Welcome to the fool's voyage in the world of 8bit emulation and basic interpreters

A blow by blow account of my futile attemps at emulating the computers, consoles and arcades I grew up with. Done for no other reason than to see if I can. If it helps others along the way, then that's a bonus!

== Introduction

So I am not really starting from scratch, I have previous !!!

Since late 2019 i have been writing code off and on around these subjects.

It started with the Cult of the bound Variable. (http://www.boundvariable.org/task.shtml). The first part of which was to write an emulator for a weird pre-historic computer, part of the 2006 ICFP programming contest. I wrote a basic emulator in Python, Go, Swift, C and C++.  

This was a great learning experience, and I was hooked. I then went on to write a CHIP-8 emulator in GO and more recently in Python. 

I then started amusing myself and wrote a basic interpreter, covering all of TinyBasic and more in C and C++, complete with full screen editor and line editor.

But none of these were ever really finished and polished, I suppose it is the priviledge of the hobbyist to be able to move on to the next shiny thing as soon as the current one becomes boring.

I restarted the whole cycle again recently in Python and, encouraged by the discovery of AsciiDoc (thank-you Oxide), I have decided to document my progress this time around, as one of the frustrations was not remembering what I had done before and having to relearn everything.

== Universal Machine v2024

Started on the 1st of August Weekend on a trip to London, the idea was initially to test how far I could go with Pythonista on the iPad, and refresh my Python knowledge.

I will move the code to github and retro document the project, but in short I got quite far, I had a working emulator and disassembler in a weekend. Which shows the strengths of Python but also the limitations of Pythonista, especially as it had re-awoken my itch for writing emulators, so I moved to my Mac for the next project.


== ChipPy




== PyRetroScreen

One of the big questions I have is what to write the emulators in. Currently I am writing them in Python, but I am not sure if this is the best language for the job. My concerns remain around speed, I dont want to write an emulator that is too slow to be workable. It would kill any fun in writing and playing with it.

Which leads to my current project PyRetroScreen, basically a test bed for screen routines to see if I can get the speed I need in Python on a screen that is 300 by 200 pixels.